// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Chat struct {
	ChatID     string `json:"chatID"`
	SenderID   string `json:"senderID"`
	ReceiverID string `json:"receiverID"`
}

type Feelr struct {
	FeelrID   string    `json:"feelrID"`
	Question  string    `json:"question"`
	Timestamp time.Time `json:"timestamp"`
	Topic     string    `json:"topic"`
	CreatedBy string    `json:"createdBy"`
}

type Message struct {
	ChatID         string    `json:"chatID"`
	SenderID       string    `json:"senderID"`
	Timestamp      time.Time `json:"timestamp"`
	Text           *string   `json:"text"`
	FeelrID        *string   `json:"feelrID"`
	SenderAnswer   *string   `json:"senderAnswer"`
	ReceiverAnswer *string   `json:"receiverAnswer"`
}

type User struct {
	UserID    string  `json:"userID"`
	UserToken *string `json:"userToken"`
	UserType  string  `json:"userType"`
	Username  string  `json:"username"`
	RelState  string  `json:"relState"`
	PartnerID *string `json:"partnerID"`
}
