// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Chat struct {
	ChatID     string `json:"chatId"`
	SenderID   string `json:"senderId"`
	ReceiverID string `json:"receiverId"`
}

type Feelr struct {
	FeelrID   string    `json:"feelrId"`
	Question  string    `json:"question"`
	Timestamp time.Time `json:"timestamp"`
	Topic     string    `json:"topic"`
}

type Message struct {
	ChatID         string    `json:"chatId"`
	SenderID       string    `json:"senderId"`
	Text           *string   `json:"text"`
	FeelrID        *string   `json:"feelrId"`
	SenderAnswer   *string   `json:"senderAnswer"`
	ReceiverAnswer *string   `json:"receiverAnswer"`
	Timestamp      time.Time `json:"timestamp"`
}

type User struct {
	UserID string `json:"userId"`
	Name   string `json:"name"`
}
